# Generated by Django 4.2.30 on 2026-06-17 16:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('meeting_code', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(max_length=50)),
                ('max_participants', models.IntegerField(default=100)),
                ('is_recording_enabled', models.BooleanField(default=False)),
                ('is_waiting_room_enabled', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meetings',
            },
        ),
        migrations.CreateModel(
            name='MeetingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_number', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('peak_participant_count', models.IntegerField(default=0)),
                ('total_duration_seconds', models.IntegerField(default=0)),
                ('recording_status', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meeting_sessions',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('webhook_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('recording_type', models.CharField(default='VIDEO', max_length=50)),
                ('storage_provider', models.CharField(default='LOCAL', max_length=50)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('processing_status', models.CharField(default='STARTED', max_length=50)),
                ('started_by', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='meetings.meetingsession')),
            ],
            options={
                'db_table': 'recordings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_user_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('role', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='meetings.product')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=50)),
                ('transcript_text', models.TextField()),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('generated_by', models.CharField(max_length=50)),
                ('processing_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='meetings.meetingsession')),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcripts', to='meetings.recording')),
            ],
            options={
                'db_table': 'transcripts',
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recurrence_type', models.CharField(max_length=50)),
                ('interval_value', models.IntegerField(default=1)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='meetings.meeting')),
            ],
            options={
                'db_table': 'recurrence_rules',
            },
        ),
        migrations.CreateModel(
            name='ProductApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key_hash', models.TextField()),
                ('environment', models.CharField(max_length=50)),
                ('rate_limit', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='meetings.product')),
            ],
            options={
                'db_table': 'product_api_keys',
            },
        ),
        migrations.CreateModel(
            name='ParticipantState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('mic_on', models.BooleanField(default=True)),
                ('video_on', models.BooleanField(default=True)),
                ('hand_raised', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_states', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_states', to='meetings.user')),
            ],
            options={
                'db_table': 'participant_states',
            },
        ),
        migrations.CreateModel(
            name='ParticipantSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('reconnect_count', models.IntegerField(default=0)),
                ('speaking_duration_seconds', models.IntegerField(default=0)),
                ('screen_share_duration_seconds', models.IntegerField(default=0)),
                ('network_avg_latency', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('meeting_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_sessions', to='meetings.meetingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='meetings.user')),
            ],
            options={
                'db_table': 'participant_sessions',
            },
        ),
        migrations.AddField(
            model_name='meetingsession',
            name='started_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_sessions', to='meetings.user'),
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('invitation_status', models.CharField(max_length=50)),
                ('joined_once', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to='meetings.user')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participations', to='meetings.user')),
            ],
            options={
                'db_table': 'meeting_participants',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to='meetings.user'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='meetings.product'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.user')),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=255)),
                ('resource_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='meetings.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='meetings.product')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
    ]
